"""
Indexes used for various stuff in Workgroup.controlls
"""
CNT_WORKERS=0
CNT_SHOULD_STOP=2
CNT_LISTEN_SOCKET=3
CNT_WORKER_COUNT=4
CNT_TASK_COUNT=5
CNT_LIVE_WORKERS=6
CNT_EVENT_COUNT=7
CNT_QUEUE_COUNT=8
CNT_TASK_EXECUTORS=9
CNT_LOCK_COUNT=10
CNT_MANAGER_COUNT=11