"""
Indexes used for various stuff in Workgroup.controlls
"""
CNT_WORKERS = "WORKERS"
CNT_LISTEN_SOCKET = "LISTEN_SOCKET"
CNT_WORKER_COUNT = "WORKER_COUNT"
CNT_TASK_COUNT = "TASK_COUNT"
CNT_TASK_EXECUTORS = "EXECUTORS"
CNT_DEAD_WORKERS = "DEAD_WORKERS"